// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.3
// source: organization.proto

package organization

import (
	common "github.com/philandz/libs/protobuf/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrgRole int32

const (
	OrgRole_OR_NONE   OrgRole = 0
	OrgRole_OR_OWNER  OrgRole = 1
	OrgRole_OR_ADMIN  OrgRole = 2
	OrgRole_OR_MEMBER OrgRole = 3
)

// Enum value maps for OrgRole.
var (
	OrgRole_name = map[int32]string{
		0: "OR_NONE",
		1: "OR_OWNER",
		2: "OR_ADMIN",
		3: "OR_MEMBER",
	}
	OrgRole_value = map[string]int32{
		"OR_NONE":   0,
		"OR_OWNER":  1,
		"OR_ADMIN":  2,
		"OR_MEMBER": 3,
	}
)

func (x OrgRole) Enum() *OrgRole {
	p := new(OrgRole)
	*p = x
	return p
}

func (x OrgRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrgRole) Descriptor() protoreflect.EnumDescriptor {
	return file_organization_proto_enumTypes[0].Descriptor()
}

func (OrgRole) Type() protoreflect.EnumType {
	return &file_organization_proto_enumTypes[0]
}

func (x OrgRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrgRole.Descriptor instead.
func (OrgRole) EnumDescriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{0}
}

type OrgStatus int32

const (
	OrgStatus_OS_NONE     OrgStatus = 0
	OrgStatus_OS_ACTIVE   OrgStatus = 1
	OrgStatus_OS_DISABLED OrgStatus = 2
)

// Enum value maps for OrgStatus.
var (
	OrgStatus_name = map[int32]string{
		0: "OS_NONE",
		1: "OS_ACTIVE",
		2: "OS_DISABLED",
	}
	OrgStatus_value = map[string]int32{
		"OS_NONE":     0,
		"OS_ACTIVE":   1,
		"OS_DISABLED": 2,
	}
)

func (x OrgStatus) Enum() *OrgStatus {
	p := new(OrgStatus)
	*p = x
	return p
}

func (x OrgStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrgStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_organization_proto_enumTypes[1].Descriptor()
}

func (OrgStatus) Type() protoreflect.EnumType {
	return &file_organization_proto_enumTypes[1]
}

func (x OrgStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrgStatus.Descriptor instead.
func (OrgStatus) EnumDescriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{1}
}

type MemberStatus int32

const (
	MemberStatus_MS_NONE    MemberStatus = 0
	MemberStatus_MS_ACTIVE  MemberStatus = 1
	MemberStatus_MS_INVITED MemberStatus = 2
)

// Enum value maps for MemberStatus.
var (
	MemberStatus_name = map[int32]string{
		0: "MS_NONE",
		1: "MS_ACTIVE",
		2: "MS_INVITED",
	}
	MemberStatus_value = map[string]int32{
		"MS_NONE":    0,
		"MS_ACTIVE":  1,
		"MS_INVITED": 2,
	}
)

func (x MemberStatus) Enum() *MemberStatus {
	p := new(MemberStatus)
	*p = x
	return p
}

func (x MemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_organization_proto_enumTypes[2].Descriptor()
}

func (MemberStatus) Type() protoreflect.EnumType {
	return &file_organization_proto_enumTypes[2]
}

func (x MemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberStatus.Descriptor instead.
func (MemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{2}
}

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.Base           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Status        OrgStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=shared.organization.OrgStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetBase() *common.Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Organization) GetStatus() OrgStatus {
	if x != nil {
		return x.Status
	}
	return OrgStatus_OS_NONE
}

type OrganizationMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgRole       OrgRole                `protobuf:"varint,3,opt,name=org_role,json=orgRole,proto3,enum=shared.organization.OrgRole" json:"org_role,omitempty"`
	Status        MemberStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=shared.organization.MemberStatus" json:"status,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMember) Reset() {
	*x = OrganizationMember{}
	mi := &file_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMember) ProtoMessage() {}

func (x *OrganizationMember) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMember.ProtoReflect.Descriptor instead.
func (*OrganizationMember) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{1}
}

func (x *OrganizationMember) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *OrganizationMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrganizationMember) GetOrgRole() OrgRole {
	if x != nil {
		return x.OrgRole
	}
	return OrgRole_OR_NONE
}

func (x *OrganizationMember) GetStatus() MemberStatus {
	if x != nil {
		return x.Status
	}
	return MemberStatus_MS_NONE
}

func (x *OrganizationMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

var File_organization_proto protoreflect.FileDescriptor

const file_organization_proto_rawDesc = "" +
	"\n" +
	"\x12organization.proto\x12\x13shared.organization\x1a\x1flibs/protobuf/common/base.proto\"\xa5\x01\n" +
	"\fOrganization\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.common.base.BaseR\x04base\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\x126\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.shared.organization.OrgStatusR\x06status\"\xd5\x01\n" +
	"\x12OrganizationMember\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x127\n" +
	"\borg_role\x18\x03 \x01(\x0e2\x1c.shared.organization.OrgRoleR\aorgRole\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2!.shared.organization.MemberStatusR\x06status\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\x03R\bjoinedAt*A\n" +
	"\aOrgRole\x12\v\n" +
	"\aOR_NONE\x10\x00\x12\f\n" +
	"\bOR_OWNER\x10\x01\x12\f\n" +
	"\bOR_ADMIN\x10\x02\x12\r\n" +
	"\tOR_MEMBER\x10\x03*8\n" +
	"\tOrgStatus\x12\v\n" +
	"\aOS_NONE\x10\x00\x12\r\n" +
	"\tOS_ACTIVE\x10\x01\x12\x0f\n" +
	"\vOS_DISABLED\x10\x02*:\n" +
	"\fMemberStatus\x12\v\n" +
	"\aMS_NONE\x10\x00\x12\r\n" +
	"\tMS_ACTIVE\x10\x01\x12\x0e\n" +
	"\n" +
	"MS_INVITED\x10\x02B:Z8github.com/philandz/philand/protobuf/shared/organizationb\x06proto3"

var (
	file_organization_proto_rawDescOnce sync.Once
	file_organization_proto_rawDescData []byte
)

func file_organization_proto_rawDescGZIP() []byte {
	file_organization_proto_rawDescOnce.Do(func() {
		file_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organization_proto_rawDesc), len(file_organization_proto_rawDesc)))
	})
	return file_organization_proto_rawDescData
}

var file_organization_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_organization_proto_goTypes = []any{
	(OrgRole)(0),               // 0: shared.organization.OrgRole
	(OrgStatus)(0),             // 1: shared.organization.OrgStatus
	(MemberStatus)(0),          // 2: shared.organization.MemberStatus
	(*Organization)(nil),       // 3: shared.organization.Organization
	(*OrganizationMember)(nil), // 4: shared.organization.OrganizationMember
	(*common.Base)(nil),        // 5: common.base.Base
}
var file_organization_proto_depIdxs = []int32{
	5, // 0: shared.organization.Organization.base:type_name -> common.base.Base
	1, // 1: shared.organization.Organization.status:type_name -> shared.organization.OrgStatus
	0, // 2: shared.organization.OrganizationMember.org_role:type_name -> shared.organization.OrgRole
	2, // 3: shared.organization.OrganizationMember.status:type_name -> shared.organization.MemberStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_organization_proto_init() }
func file_organization_proto_init() {
	if File_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_proto_rawDesc), len(file_organization_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organization_proto_goTypes,
		DependencyIndexes: file_organization_proto_depIdxs,
		EnumInfos:         file_organization_proto_enumTypes,
		MessageInfos:      file_organization_proto_msgTypes,
	}.Build()
	File_organization_proto = out.File
	file_organization_proto_goTypes = nil
	file_organization_proto_depIdxs = nil
}
