// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Organization {
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<super::super::common::base::Base>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(enumeration = "OrgStatus", tag = "4")]
    pub status: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrganizationMember {
    #[prost(string, tag = "1")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(enumeration = "OrgRole", tag = "3")]
    pub org_role: i32,
    #[prost(enumeration = "MemberStatus", tag = "4")]
    pub status: i32,
    #[prost(int64, tag = "5")]
    pub joined_at: i64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrgRole {
    OrNone = 0,
    OrOwner = 1,
    OrAdmin = 2,
    OrMember = 3,
}
impl OrgRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::OrNone => "OR_NONE",
            Self::OrOwner => "OR_OWNER",
            Self::OrAdmin => "OR_ADMIN",
            Self::OrMember => "OR_MEMBER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OR_NONE" => Some(Self::OrNone),
            "OR_OWNER" => Some(Self::OrOwner),
            "OR_ADMIN" => Some(Self::OrAdmin),
            "OR_MEMBER" => Some(Self::OrMember),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrgStatus {
    OsNone = 0,
    OsActive = 1,
    OsDisabled = 2,
}
impl OrgStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::OsNone => "OS_NONE",
            Self::OsActive => "OS_ACTIVE",
            Self::OsDisabled => "OS_DISABLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OS_NONE" => Some(Self::OsNone),
            "OS_ACTIVE" => Some(Self::OsActive),
            "OS_DISABLED" => Some(Self::OsDisabled),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MemberStatus {
    MsNone = 0,
    MsActive = 1,
    MsInvited = 2,
}
impl MemberStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::MsNone => "MS_NONE",
            Self::MsActive => "MS_ACTIVE",
            Self::MsInvited => "MS_INVITED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MS_NONE" => Some(Self::MsNone),
            "MS_ACTIVE" => Some(Self::MsActive),
            "MS_INVITED" => Some(Self::MsInvited),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
