// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.3
// source: libs/protobuf/common/base.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseStatus int32

const (
	BaseStatus_BS_NONE     BaseStatus = 0
	BaseStatus_BS_ACTIVE   BaseStatus = 1
	BaseStatus_BS_INACTIVE BaseStatus = 2
	BaseStatus_BS_PENDING  BaseStatus = 3
	BaseStatus_BS_DELETED  BaseStatus = 4
	BaseStatus_BS_ARCHIVED BaseStatus = 5
	BaseStatus_BS_BLOCKED  BaseStatus = 6
	BaseStatus_BS_UNKNOWN  BaseStatus = 7
)

// Enum value maps for BaseStatus.
var (
	BaseStatus_name = map[int32]string{
		0: "BS_NONE",
		1: "BS_ACTIVE",
		2: "BS_INACTIVE",
		3: "BS_PENDING",
		4: "BS_DELETED",
		5: "BS_ARCHIVED",
		6: "BS_BLOCKED",
		7: "BS_UNKNOWN",
	}
	BaseStatus_value = map[string]int32{
		"BS_NONE":     0,
		"BS_ACTIVE":   1,
		"BS_INACTIVE": 2,
		"BS_PENDING":  3,
		"BS_DELETED":  4,
		"BS_ARCHIVED": 5,
		"BS_BLOCKED":  6,
		"BS_UNKNOWN":  7,
	}
)

func (x BaseStatus) Enum() *BaseStatus {
	p := new(BaseStatus)
	*p = x
	return p
}

func (x BaseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_libs_protobuf_common_base_proto_enumTypes[0].Descriptor()
}

func (BaseStatus) Type() protoreflect.EnumType {
	return &file_libs_protobuf_common_base_proto_enumTypes[0]
}

func (x BaseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaseStatus.Descriptor instead.
func (BaseStatus) EnumDescriptor() ([]byte, []int) {
	return file_libs_protobuf_common_base_proto_rawDescGZIP(), []int{0}
}

type Base struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	OwnerId       string                 `protobuf:"bytes,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Status        BaseStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=common.base.BaseStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base) Reset() {
	*x = Base{}
	mi := &file_libs_protobuf_common_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_libs_protobuf_common_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_libs_protobuf_common_base_proto_rawDescGZIP(), []int{0}
}

func (x *Base) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Base) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Base) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Base) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *Base) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Base) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Base) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Base) GetStatus() BaseStatus {
	if x != nil {
		return x.Status
	}
	return BaseStatus_BS_NONE
}

var File_libs_protobuf_common_base_proto protoreflect.FileDescriptor

const file_libs_protobuf_common_base_proto_rawDesc = "" +
	"\n" +
	"\x1flibs/protobuf/common/base.proto\x12\vcommon.base\"\xfd\x01\n" +
	"\x04Base\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\x03R\tdeletedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x06 \x01(\tR\tupdatedBy\x12\x19\n" +
	"\bowner_id\x18\a \x01(\tR\aownerId\x12/\n" +
	"\x06status\x18\b \x01(\x0e2\x17.common.base.BaseStatusR\x06status*\x8a\x01\n" +
	"\n" +
	"BaseStatus\x12\v\n" +
	"\aBS_NONE\x10\x00\x12\r\n" +
	"\tBS_ACTIVE\x10\x01\x12\x0f\n" +
	"\vBS_INACTIVE\x10\x02\x12\x0e\n" +
	"\n" +
	"BS_PENDING\x10\x03\x12\x0e\n" +
	"\n" +
	"BS_DELETED\x10\x04\x12\x0f\n" +
	"\vBS_ARCHIVED\x10\x05\x12\x0e\n" +
	"\n" +
	"BS_BLOCKED\x10\x06\x12\x0e\n" +
	"\n" +
	"BS_UNKNOWN\x10\aB*Z(github.com/philandz/libs/protobuf/commonb\x06proto3"

var (
	file_libs_protobuf_common_base_proto_rawDescOnce sync.Once
	file_libs_protobuf_common_base_proto_rawDescData []byte
)

func file_libs_protobuf_common_base_proto_rawDescGZIP() []byte {
	file_libs_protobuf_common_base_proto_rawDescOnce.Do(func() {
		file_libs_protobuf_common_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libs_protobuf_common_base_proto_rawDesc), len(file_libs_protobuf_common_base_proto_rawDesc)))
	})
	return file_libs_protobuf_common_base_proto_rawDescData
}

var file_libs_protobuf_common_base_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_libs_protobuf_common_base_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_libs_protobuf_common_base_proto_goTypes = []any{
	(BaseStatus)(0), // 0: common.base.BaseStatus
	(*Base)(nil),    // 1: common.base.Base
}
var file_libs_protobuf_common_base_proto_depIdxs = []int32{
	0, // 0: common.base.Base.status:type_name -> common.base.BaseStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_libs_protobuf_common_base_proto_init() }
func file_libs_protobuf_common_base_proto_init() {
	if File_libs_protobuf_common_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libs_protobuf_common_base_proto_rawDesc), len(file_libs_protobuf_common_base_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libs_protobuf_common_base_proto_goTypes,
		DependencyIndexes: file_libs_protobuf_common_base_proto_depIdxs,
		EnumInfos:         file_libs_protobuf_common_base_proto_enumTypes,
		MessageInfos:      file_libs_protobuf_common_base_proto_msgTypes,
	}.Build()
	File_libs_protobuf_common_base_proto = out.File
	file_libs_protobuf_common_base_proto_goTypes = nil
	file_libs_protobuf_common_base_proto_depIdxs = nil
}
