// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct User {
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<super::super::common::base::Base>,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub password_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(enumeration = "UserType", tag = "5")]
    pub user_type: i32,
    #[prost(enumeration = "UserStatus", tag = "6")]
    pub status: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UserType {
    /// Default value must be 0
    UtNone = 0,
    UtNormal = 1,
    UtSuperAdmin = 2,
}
impl UserType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UtNone => "UT_NONE",
            Self::UtNormal => "UT_NORMAL",
            Self::UtSuperAdmin => "UT_SUPER_ADMIN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UT_NONE" => Some(Self::UtNone),
            "UT_NORMAL" => Some(Self::UtNormal),
            "UT_SUPER_ADMIN" => Some(Self::UtSuperAdmin),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UserStatus {
    UsNone = 0,
    UsActive = 1,
    UsDisabled = 2,
}
impl UserStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UsNone => "US_NONE",
            Self::UsActive => "US_ACTIVE",
            Self::UsDisabled => "US_DISABLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "US_NONE" => Some(Self::UsNone),
            "US_ACTIVE" => Some(Self::UsActive),
            "US_DISABLED" => Some(Self::UsDisabled),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
