// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Base {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub created_at: i64,
    #[prost(int64, tag = "3")]
    pub updated_at: i64,
    #[prost(int64, tag = "4")]
    pub deleted_at: i64,
    #[prost(string, tag = "5")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub updated_by: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub owner_id: ::prost::alloc::string::String,
    #[prost(enumeration = "BaseStatus", tag = "8")]
    pub status: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BaseStatus {
    BsNone = 0,
    BsActive = 1,
    BsInactive = 2,
    BsPending = 3,
    BsDeleted = 4,
    BsArchived = 5,
    BsBlocked = 6,
    BsUnknown = 7,
}
impl BaseStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::BsNone => "BS_NONE",
            Self::BsActive => "BS_ACTIVE",
            Self::BsInactive => "BS_INACTIVE",
            Self::BsPending => "BS_PENDING",
            Self::BsDeleted => "BS_DELETED",
            Self::BsArchived => "BS_ARCHIVED",
            Self::BsBlocked => "BS_BLOCKED",
            Self::BsUnknown => "BS_UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BS_NONE" => Some(Self::BsNone),
            "BS_ACTIVE" => Some(Self::BsActive),
            "BS_INACTIVE" => Some(Self::BsInactive),
            "BS_PENDING" => Some(Self::BsPending),
            "BS_DELETED" => Some(Self::BsDeleted),
            "BS_ARCHIVED" => Some(Self::BsArchived),
            "BS_BLOCKED" => Some(Self::BsBlocked),
            "BS_UNKNOWN" => Some(Self::BsUnknown),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
